import os

# AJUSTES JUEGO
FPS = 30
DIFICULTAD_INI = 5
VIDAS = 3
HABILITAR_MOV_DER_IZQ = False

# AJUSTES PANTALLA
ANCHO = 1200
ALTO = 800
CENTRO_Y = ALTO / 2
CENTRO_X = ANCHO / 2
MARGEN_IZQ = 60
MARGEN_SUP = 60
MARGEN_INF = ALTO - 60

# TAMAÑO FUENTES ESCALADA SEGÚN LA PANTALLA
TAM_FUENTE_1 = int((ANCHO * ALTO) / 60000)
TAM_FUENTE_2 = int((ANCHO * ALTO) / 40000)
TAM_FUENTE_3 = int((ANCHO * ALTO) / 20000)
TAM_FUENTE_4 = int((ANCHO * ALTO) / 10000)

# RUTAS FUENTES
FUENTE_NASA = os.path.join('resources', 'fonts', 'nasa.otf')
FUENTE_CONTRAST = os.path.join('resources', 'fonts', 'contrast.ttf')

# COLORES
ROJO = (99, 0, 0)
VERDE = (0, 99, 0)
AZUL = (0, 0, 99)
BLANCO = (255, 255, 255)
